version: '3'

services:
################################################################################
  transmission:
    image: haugene/transmission-openvpn:latest-armhf
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
      - "8989:8989" #sonarr
      - "9117:9117" #jackett
      - "7878:7878" #radarr
      - "8686:8686" #lidarr
      # - "8080:8080" #kodi webui
      # - "9090:9090" #kodi websockets
      # - "9777:9777" #kodi esall interface
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/docker/transmission-openvpn/data/:/data
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - TRANSMISSION_WEB_UI=combustion
################################################################################
  sonarr:
    image: linuxserver/sonarr:arm32v7-latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
    volumes:
      - ${MOUNT_POINT}/docker/sonarr/config/:/config
      - ${MOUNT_POINT}/docker/sonarr/data/tv/:/tv
      - ${MOUNT_POINT}/docker/sonarr/data/downloads/:/downloads
    restart: unless-stopped
    network_mode: "service:transmission"
################################################################################
  jackett:
      image: linuxserver/jackett:arm32v7-latest
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Canada/Mountain
        # - RUN_OPTS= #optional
      volumes:
        - ${MOUNT_POINT}/docker/jackett/config/:/config
        - ${MOUNT_POINT}/docker/jackett/downloads/:/downloads
      restart: unless-stopped
      network_mode: "service:transmission"
################################################################################
  radarr:
    image: linuxserver/radarr:arm32v7-latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
    volumes:
      - ${MOUNT_POINT}/docker/radarr/config/:/config
      - ${MOUNT_POINT}/docker/radarr/movies/:/movies
      - ${MOUNT_POINT}/docker/radarr/downloads/:/downloads
    restart: unless-stopped
    network_mode: "service:transmission"
################################################################################
  lidarr:
      image: linuxserver/lidarr:arm32v7-latest
      container_name: lidarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Canada/Mountain
      volumes:
        - ${MOUNT_POINT}/docker/lidarr/config/:/config
        - ${MOUNT_POINT}/docker/lidarr/music/:/music
        - ${MOUNT_POINT}/docker/lidarr/downloads/:/downloads
      restart: unless-stopped
      network_mode: "service:transmission"
################################################################################
  # kodi:
  #   image: lsioarmhf/kodi-headless:latest
  #   container_name: kodi
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Canada/Mountain
  #   volumes:
  #     - ${MOUNT_POINT}/docker/kodi/config/:/config
  #   restart: unless-stopped
  #   network_mode: "service:transmission"
################################################################################
