version: '3'

services:
################################################################################
  transmission:
    image: haugene/transmission-openvpn:latest-alpine
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "8888:8888"
      - "8989:8989" #sonarr
      - "9117:9117" #jackett
      - "7878:7878" #radarr
      - "8686:8686" #lidarr
      - "8096:8096" #jellyfin
      - "8200:8200" #duplicati
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/data/transmission-openvpn/data/:/data
      - ${MOUNT_POINT}/data/downloads/:/downloads
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_BLOCKLIST_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz
      - TRANSMISSION_PEER_LIMIT_GLOBAL=2000
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
      - TRANSMISSION_QUEUE_STALLED_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
################################################################################
  jackett:
      image: linuxserver/jackett:latest
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Canada/Mountain
        # - RUN_OPTS= #optional
      volumes:
        - ${MOUNT_POINT}/jackett/config/:/config
        - ${MOUNT_POINT}/downloads/:/downloads
      restart: unless-stopped
      network_mode: "service:transmission"
      depends_on:
        - transmission
################################################################################
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
    volumes:
      - ${MOUNT_POINT}/sonarr/config/:/config
      - ${MOUNT_POINT}/data/tv/:/tv
      - ${MOUNT_POINT}/data/downloads/:/downloads
    restart: unless-stopped
    network_mode: "service:transmission"
    depends_on:
      - transmission
      - jackett
################################################################################
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
    volumes:
      - ${MOUNT_POINT}/radarr/config/:/config
      - ${MOUNT_POINT}/data/movies/:/movies
      - ${MOUNT_POINT}/data/downloads/:/downloads
    restart: unless-stopped
    network_mode: "service:transmission"
    depends_on:
      - transmission
      - jackett
################################################################################
  lidarr:
      image: linuxserver/lidarr:latest
      container_name: lidarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Canada/Mountain
      volumes:
        - ${MOUNT_POINT}/lidarr/config/:/config
        - ${MOUNT_POINT}/data/music/:/music
        - ${MOUNT_POINT}/data/downloads/:/downloads
      restart: unless-stopped
      network_mode: "service:transmission"
      depends_on:
      - transmission
      - jackett
################################################################################
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
      # - UMASK_SET=022 #optional
    volumes:
      - ${MOUNT_POINT}/jellyfin/config/:/config
      - ${MOUNT_POINT}/data/tv/:/data/tvshows
      - ${MOUNT_POINT}/data/movies/:/data/movies
      # - /path for transcoding:/transcode #optional
    # ports:
    #   - 8096:8096
    #   # - 8920:8920 #optional
    restart: unless-stopped
    network_mode: "service:transmission"
    depends_on:
      - transmission
################################################################################
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
    # environment:
    volumes:
      - ${MOUNT_POINT}/duplicati/config:/config
      - ${MOUNT_POINT}/duplicati/backups/:/backups
      - ${MOUNT_POINT}/:/source
    # ports:
    #   - 8200:8200
    restart: unless-stopped
    network_mode: "service:transmission"
    depends_on:
      - transmission
################################################################################
